(() => {
  const ENDPOINT='https://uehmbzwnbariqebbxcst.supabase.co/functions/v1/trip-stay-extras';
  let loadedKey='', extras=null, busy=false;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>Number.isFinite(Number(n))?new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(n)):'—';
  const minsLabel=n=>{n=Number(n)||0;const h=Math.floor(n/60),m=n%60;return h?`${h} hr${h===1?'':'s'} ${m?`${m} min`:''}`:`${m} min`};
  const eventNow=()=>Array.isArray(events)?events.find(e=>e.id===state?.confirmedEventId):null;
  const booked=()=>((state?.bookings)||[]).filter(b=>b.event_id===state?.confirmedEventId&&(b.attendance_status||'booked')==='booked');
  const detailFor=id=>((state?.tripDetails)||[]).find(r=>r.event_id===state?.confirmedEventId&&r.member_id===id);
  const memberName=id=>((state?.members)||[]).find(m=>m.id===id)?.name||'Driver';
  function split(){const rows=booked().map(b=>{const p=(detailFor(b.member_id)?.passenger_names||[]).filter(Boolean).length;return{name:memberName(b.member_id),people:1+p}});const people=rows.reduce((a,r)=>a+r.people,0),total=Number(extras?.total_cost||0),each=people&&total?total/people:0;return{rows,people,total,each}}
  async function req(method='GET',payload={}){if(!session?.groupId||!session?.memberToken||!state?.confirmedEventId)return null;if(method==='GET'){const q=new URLSearchParams({groupId:session.groupId,token:session.memberToken,eventId:state.confirmedEventId});const r=await fetch(`${ENDPOINT}?${q}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load stay details');return j}const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({groupId:session.groupId,token:session.memberToken,eventId:state.confirmedEventId,...payload})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save stay details');return j}
  const waze=q=>`https://waze.com/ul?q=${encodeURIComponent(q)}&navigate=yes`;
  const isConfirmed=()=>!!(extras&&(extras.postcode||extras.total_cost||extras.checkin_text||extras.checkout_text));
  function cardHtml(){
    const s=split(),acc=state?.accommodation||{},e=eventNow(),confirmed=isConfirmed(),destination=(extras?.postcode||acc.address||acc.location||'').trim(),start=(extras?.crew_start||'St Austell, Cornwall').trim();
    const r1=extras?.route_from_start_miles!=null?`${extras.route_from_start_miles} mi · ${minsLabel(extras.route_from_start_minutes)}`:'Calculate after import';
    const r2=extras?.route_to_track_miles!=null?`${extras.route_to_track_miles} mi · ${minsLabel(extras.route_to_track_minutes)}`:'Calculate after import';
    const summary=confirmed?`<div class="stay-confirmed" data-stay-confirmed><div><span class="accommodation-label">CONFIRMED STAY</span><strong>${esc(acc.location||'Accommodation')}</strong><span>${esc(acc.address||extras?.postcode||'')}</span>${extras?.checkin_text?`<span>Check-in: ${esc(extras.checkin_text)}</span>`:''}${extras?.checkout_text?`<span>Checkout: ${esc(extras.checkout_text)}</span>`:''}</div><button type="button" class="ghost" data-edit-stay>Edit stay details</button></div>`:'';
    const editor=`<div data-stay-editor ${confirmed?'hidden':''}><p class="stay-extras-copy">Import up to three Airbnb screenshots, check what Heros found, then save it once.</p><input type="file" accept="image/*" multiple data-airbnb-files hidden><button type="button" class="ghost wide" data-airbnb-import>📸 Import Airbnb screenshots</button><div class="stay-import-status" data-airbnb-status></div><form class="stay-import-form" data-airbnb-form ${confirmed?'':'hidden'}><label>Property / area<input name="location" value="${esc(acc.location||'')}"></label><label>Address<input name="address" value="${esc(acc.address||'')}"></label><div class="stay-import-two"><label>Postcode<input name="postcode" value="${esc(extras?.postcode||'')}"></label><label>Total cost (£)<input name="totalCost" inputmode="decimal" value="${esc(extras?.total_cost||'')}"></label></div><div class="stay-import-two"><label>Check-in<input name="checkin" value="${esc(extras?.checkin_text||'')}"></label><label>Checkout<input name="checkout" value="${esc(extras?.checkout_text||'')}"></label></div><label>Crew start<input name="crewStart" value="${esc(start)}"></label><div class="stay-import-actions"><button type="submit" class="primary">Use these details →</button><button type="button" class="ghost" data-airbnb-cancel>Cancel</button></div></form></div>`;
    return `<section class="trip-mode-card stay-extras-card" data-stay-extras><div class="stay-extras-head"><div><span class="eyebrow">ACCOMMODATION</span><h2>🏠 Stay details</h2></div><a class="airbnb-link" href="https://www.airbnb.co.uk/" target="_blank" rel="noopener">Open Airbnb ↗</a></div>${summary}${editor}${s.total?`<div class="stay-money"><span class="accommodation-label">COST SPLIT</span><strong>${money(s.total)} total · ${s.people} paying · ${money(s.each)} each</strong>${s.rows.map(r=>`<div><span>${esc(r.name)}${r.people>1?` + ${r.people-1} passenger${r.people>2?'s':''}`:''}</span><b>${money(r.people*s.each)}</b></div>`).join('')}</div>`:''}<div class="stay-routes"><span class="accommodation-label">TRAVEL</span><div class="stay-route"><div><strong>${esc(start)} → Accommodation</strong><span>${esc(r1)}</span></div>${destination?`<a class="waze-btn" href="${waze(destination)}" target="_blank" rel="noopener">Waze →</a>`:''}</div><div class="stay-route"><div><strong>Accommodation → ${esc(e?.track||'Track')}</strong><span>${esc(r2)}</span></div>${e?.track?`<a class="waze-btn" href="${waze(`${e.track} Circuit, UK`)}" target="_blank" rel="noopener">Waze →</a>`:''}</div></div></section>`;
  }
  function style(){if(document.querySelector('#stay-extras-style'))return;const s=document.createElement('style');s.id='stay-extras-style';s.textContent=`.stay-extras-card{margin-top:14px}.stay-extras-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.stay-extras-head h2{margin:4px 0 0;font-size:25px}.stay-extras-copy{color:#9aa4ae;font-size:12px;line-height:1.5}.stay-confirmed{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;margin-top:16px;padding:14px;border:1px solid #2d4737;border-radius:14px;background:#101a14}.stay-confirmed strong{display:block;font-size:16px;margin:3px 0}.stay-confirmed span:not(.accommodation-label){display:block;color:#9aa6a0;font-size:11px;margin-top:3px}.stay-import-status{font-size:11px;color:#72df9e;margin-top:9px;min-height:16px}.stay-import-form{display:grid;gap:11px;margin-top:12px;padding-top:13px;border-top:1px solid #2b323a}.stay-import-form label{display:grid;gap:6px;font-size:11px;font-weight:800;color:#c7cfd8}.stay-import-form input{width:100%;box-sizing:border-box}.stay-import-two{display:grid;grid-template-columns:1fr 1fr;gap:9px}.stay-import-actions{display:flex;gap:8px;flex-wrap:wrap}.stay-money,.stay-routes{margin-top:16px;padding-top:14px;border-top:1px solid #2b323a}.stay-money>strong{display:block;font-size:16px;margin:4px 0 9px}.stay-money>div{display:flex;justify-content:space-between;gap:10px;padding:7px 0;border-top:1px solid #222930;font-size:12px}.stay-route{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-top:1px solid #222930}.stay-route strong{display:block;font-size:13px}.stay-route span{display:block;color:#89949f;font-size:11px;margin-top:3px}.waze-btn{flex:none;text-decoration:none;border:1px solid #3b4650;border-radius:10px;padding:9px 11px;color:#fff;font-size:11px;font-weight:900;background:#171d22}@media(max-width:620px){.stay-import-two{grid-template-columns:1fr}.stay-route{align-items:flex-start}.waze-btn{padding:9px 10px}.stay-extras-head{flex-direction:column}.stay-extras-head .airbnb-link{width:100%;box-sizing:border-box}.stay-confirmed{flex-direction:column}.stay-confirmed button{width:100%}}`;document.head.appendChild(s)}
  function parseText(text){const lines=text.split(/\n+/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);const postcode=(text.match(/\b([A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2})\b/i)||[])[1]||'';const costs=[...text.matchAll(/£\s*([0-9][0-9,]*(?:\.\d{1,2})?)/g)].map(m=>Number(m[1].replace(/,/g,''))).filter(n=>Number.isFinite(n)&&n>0),totalCost=costs.length?Math.max(...costs):'';const home=lines.find(x=>/^Home in /i.test(x)),area=home?home.replace(/^Home in /i,'').trim():'';const yourPlace=lines.findIndex(x=>/^Your place$/i.test(x));let property='';if(yourPlace>=0)property=(lines[yourPlace+1]||'').split('|')[0].trim();if(!property){const p=lines.find(x=>/\b(?:House|Cottage|Lodge|Apartment|Flat|Barn)\b/i.test(x)&&!/house manual|home in/i.test(x));if(p)property=p.split('|')[0].trim()}const location=property||area,address=property?(postcode?`${property}, ${postcode.toUpperCase()}`:property):'';const dateMatches=[...text.matchAll(/\b(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sept?|Oct|Nov|Dec)\b/gi)].map(m=>m[0]);const timeMatches=[...text.matchAll(/\b(?:[01]?\d|2[0-3]):[0-5]\d\b/g)].map(m=>m[0]).filter(t=>!/^16:|^17:|^18:|^19:|^20:|^21:|^22:|^23:/.test(t));let checkin='',checkout='';if(dateMatches.length>=2){checkin=`${dateMatches[0]}${timeMatches[0]?` · ${timeMatches[0]}`:''}`;checkout=`${dateMatches[1]}${timeMatches[1]?` · ${timeMatches[1]}`:''}`}return{postcode:postcode.toUpperCase(),totalCost,checkin,checkout,location,address}}
  async function loadTesseract(status){if(window.Tesseract)return window.Tesseract;status.textContent='Loading screenshot reader…';await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';sc.onload=resolve;sc.onerror=()=>reject(new Error('Could not load screenshot reader'));document.head.appendChild(sc)});return window.Tesseract}
  async function importFiles(files,card){if(busy||!files.length)return;busy=true;const status=card.querySelector('[data-airbnb-status]');try{const T=await loadTesseract(status);let text='';for(let i=0;i<Math.min(files.length,3);i++){status.textContent=`Reading screenshot ${i+1} of ${Math.min(files.length,3)}…`;const result=await T.recognize(files[i],'eng',{logger:m=>{if(m.status==='recognizing text'&&m.progress)status.textContent=`Reading screenshot ${i+1} · ${Math.round(m.progress*100)}%`}});text+='\n'+(result?.data?.text||'')}const p=parseText(text),form=card.querySelector('[data-airbnb-form]');for(const [n,v] of Object.entries({location:p.location,address:p.address,postcode:p.postcode,totalCost:p.totalCost,checkin:p.checkin,checkout:p.checkout})){if(v&&form.elements[n])form.elements[n].value=v}form.hidden=false;status.textContent='Details found ✓ Check them, then save.'}catch(e){status.textContent=`Could not read screenshots: ${e.message||e}`}finally{busy=false}}
  async function saveForm(form,card){const fd=new FormData(form),status=card.querySelector('[data-airbnb-status]'),btn=form.querySelector('[type="submit"]');btn.disabled=true;btn.textContent='Saving…';try{const location=String(fd.get('location')||'').trim(),address=String(fd.get('address')||'').trim(),postcode=String(fd.get('postcode')||'').trim(),checkin=String(fd.get('checkin')||'').trim(),checkout=String(fd.get('checkout')||'').trim(),crewStart=String(fd.get('crewStart')||'St Austell, Cornwall').trim(),totalCost=Number(String(fd.get('totalCost')||'').replace(/[^0-9.]/g,''))||null,old=state?.accommodation||{},stayDetails=[checkin?`Check-in: ${checkin}`:'',checkout?`Checkout: ${checkout}`:''].filter(Boolean).join('\n')||old.stay_details||'';await api('save-accommodation','POST',{groupId:session.groupId,token:session.memberToken,eventId:state.confirmedEventId,location:location||old.location||'',address:address||old.address||'',stayDetails,parkingNotes:old.parking_notes||''});let routeData=null;const track=eventNow()?.track||'',accommodation=postcode||address||location;if(crewStart&&accommodation&&track){status.textContent='Calculating routes…';try{routeData=await req('POST',{action:'route',start:crewStart,accommodation,track:`${track} Circuit, UK`})}catch(e){console.warn('Route calculation failed',e)}}const payload={postcode,totalCost,checkinText:checkin,checkoutText:checkout,crewStart,routeFromStartMiles:routeData?.fromStart?.miles??null,routeFromStartMinutes:routeData?.fromStart?.minutes??null,routeToTrackMiles:routeData?.toTrack?.miles??null,routeToTrackMinutes:routeData?.toTrack?.minutes??null},j=await req('POST',payload);extras=j?.extras||payload;await loadGroup();renderAll();setTimeout(()=>document.querySelector('[data-trip-tab="stay"]')?.click(),80)}catch(e){status.textContent=`Could not save: ${e.message||e}`;btn.disabled=false;btn.textContent='Use these details →'}}
  function wire(card){const input=card.querySelector('[data-airbnb-files]'),button=card.querySelector('[data-airbnb-import]'),form=card.querySelector('[data-airbnb-form]'),editor=card.querySelector('[data-stay-editor]'),summary=card.querySelector('[data-stay-confirmed]');if(button)button.onclick=()=>input.click();if(input)input.onchange=()=>importFiles([...input.files],card);card.querySelector('[data-airbnb-cancel]')?.addEventListener('click',()=>{form.hidden=true;if(isConfirmed()){editor.hidden=true;if(summary)summary.hidden=false}});card.querySelector('[data-edit-stay]')?.addEventListener('click',()=>{editor.hidden=false;form.hidden=false;if(summary)summary.hidden=true});if(form)form.onsubmit=e=>{e.preventDefault();saveForm(form,card)}}
  function renderAll(){document.querySelectorAll('.trip-mode-shell').forEach(shell=>{const stay=shell.querySelector('[data-trip-panel="stay"]');if(!stay)return;stay.querySelector('.trip-accommodation')?.remove();stay.querySelector('[data-stay-extras]')?.remove();const wrap=document.createElement('div');wrap.innerHTML=cardHtml();const card=wrap.firstElementChild;stay.appendChild(card);wire(card)})}
  async function load(){const key=`${session?.groupId||''}:${state?.confirmedEventId||''}`;if(!state?.confirmedEventId||!session?.memberToken)return;if(key===loadedKey)return;loadedKey=key;try{const j=await req('GET');extras=j?.extras||null}catch(e){console.warn('Stay extras load failed',e)}renderAll()}
  function tick(){style();load();document.querySelectorAll('.trip-mode-shell').forEach(shell=>{const stay=shell.querySelector('[data-trip-panel="stay"]');if(!stay)return;stay.querySelector('.trip-accommodation')?.remove();if(!stay.querySelector('[data-stay-extras]'))renderAll()})}setInterval(tick,900);tick();
})();