const seed={members:[{name:'Dave',car:'Clio 172',ready:true},{name:'Tommy',car:'Civic Type R',ready:false},{name:'Frank',car:'Civic Type R',ready:false},{name:'Dex',car:'Track car',ready:false},{name:'Joe',car:'Porsche GT4',ready:false}],availability:{},votes:{},winner:null};
const events=[{id:'com',day:28,month:'SEP',date:'2026-09-28',track:'Castle Combe',provider:'Javelin',price:179,format:'Open pit lane',score:5},{id:'thr',day:30,month:'SEP',date:'2026-09-30',track:'Thruxton',provider:'Trackdays',price:199,format:'90 dB',score:4},{id:'don',day:5,month:'OCT',date:'2026-10-05',track:'Donington Park',provider:'Circuit Days',price:229,format:'Open pit lane',score:4}];
let state=JSON.parse(localStorage.getItem('tdp-state')||'null')||structuredClone(seed); const save=()=>{localStorage.setItem('tdp-state',JSON.stringify(state));render()};
function renderMembers(){document.querySelector('#memberList').innerHTML=state.members.map((m,i)=>`<div class="member"><div class="avatar">${m.name[0]}</div><div class="member-info"><strong>${m.name}</strong><span>${m.car||'Car not set'}</span></div><span class="ready">${m.ready?'DATES IN':'WAITING'}</span></div>`).join('')}
const days=['M','T','W','T','F','S','S']; function renderCalendar(){let html=`<div class="calendar-head"><strong>September 2026</strong><span class="muted">tap to mark</span></div><div class="calendar-grid">${days.map(x=>`<div class="dow">${x}</div>`).join('')}`;for(let i=0;i<1;i++)html+='<span class="day empty"></span>';for(let d=1;d<=30;d++){let key=`2026-09-${String(d).padStart(2,'0')}`,v=state.availability[key]||'';html+=`<button class="day ${v}" data-date="${key}">${d}</button>`}html+='</div>';document.querySelector('#calendar').innerHTML=html;document.querySelectorAll('.day[data-date]').forEach(b=>b.onclick=()=>{let v=state.availability[b.dataset.date];state.availability[b.dataset.date]=v==='yes'?'maybe':v==='maybe'?'':'yes';state.members[0].ready=Object.values(state.availability).some(Boolean);save()})}
function eventCard(e,withVote=false){let votes=Object.values(state.votes).filter(v=>v===e.id).length;return `<article class="card event"><div class="datebox"><strong>${e.day}</strong><span>${e.month} 2026</span></div><div><h3>${e.track}</h3><div class="meta">${e.provider} · ${e.format} · £${e.price}</div>${withVote?`<div class="vote-row"><button data-vote="${e.id}" class="${state.votes.Dave===e.id?'selected':''}">Vote for this</button></div>`:''}</div><div class="score"><strong>${withVote?votes:e.score}/${state.members.length}</strong><span class="meta">${withVote?'votes':'available'}</span></div></article>`}
function renderMatches(){document.querySelector('#matchList').innerHTML=events.map(e=>eventCard(e)).join('')}
function renderVotes(){document.querySelector('#voteList').innerHTML=events.map(e=>eventCard(e,true)).join('');document.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{state.votes.Dave=b.dataset.vote;save()});let n=Object.keys(state.votes).length,total=state.members.length;document.querySelector('#voteStatus').textContent=`${n}/${total} VOTED`;let counts={};Object.values(state.votes).forEach(v=>counts[v]=(counts[v]||0)+1);let max=Math.max(0,...Object.values(counts));let winners=Object.keys(counts).filter(k=>counts[k]===max);document.querySelector('#confirmWinnerBtn').disabled=!winners.length;document.querySelector('#confirmWinnerBtn').dataset.winner=winners[0]||''}
function renderTrip(){let e=events.find(x=>x.id===state.winner)||events[0];document.querySelector('#tripSummary').innerHTML=`<div class="trip-grid"><div class="card"><span class="eyebrow">TRACK DAY</span><h2>${e.track}</h2><p>${e.day} ${e.month} 2026 · ${e.provider} · £${e.price}</p><span class="pill success">TRACK SELECTED</span></div><div class="card"><span class="eyebrow">HEADCOUNT</span><h3>Drivers & passengers</h3>${state.members.map((m,i)=>`<div class="attendance-row"><span>${m.name}</span><select data-att="${i}"><option>Driver only</option><option>Driver +1</option><option>Driver +2</option><option>Not attending</option></select></div>`).join('')}</div><div class="card"><span class="eyebrow">ACCOMMODATION</span><h3>Who needs a bed?</h3><p class="muted">Night-before / night-after requirements feed the accommodation search so the app books for the real headcount.</p><button class="wide">Find accommodation →</button></div><div class="card"><span class="eyebrow">NEXT ACTION</span><h3>Get everyone booked</h3><p class="muted">Booking status, non-responders and payment tracking will live here.</p></div></div>`}
function progress(){let p=state.winner?100:state.votes.Dave?70:state.members[0].ready?35:10;document.querySelector('#progressValue').textContent=p+'%'}
function render(){renderMembers();renderCalendar();renderMatches();renderVotes();renderTrip();progress()}
function stage(id){document.querySelectorAll('.stage,.steps button').forEach(x=>x.classList.remove('active'));document.querySelector('#'+id).classList.add('active');document.querySelector(`[data-stage="${id}"]`).classList.add('active');scrollTo({top:250,behavior:'smooth'})}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>stage(b.dataset.stage));document.querySelector('#findBtn').onclick=()=>stage('matches');document.querySelector('#matchList').onclick=()=>stage('vote');document.querySelector('#confirmWinnerBtn').onclick=e=>{state.winner=e.currentTarget.dataset.winner;save();stage('trip')};
const dlg=document.querySelector('#memberDialog');document.querySelector('#addMemberBtn').onclick=()=>dlg.showModal();document.querySelector('#memberForm').onsubmit=e=>{e.preventDefault();let name=document.querySelector('#memberName').value.trim();if(name){state.members.push({name,car:document.querySelector('#memberCar').value.trim(),ready:false});save();dlg.close();e.target.reset()}};document.querySelector('#resetBtn').onclick=()=>{state=structuredClone(seed);localStorage.removeItem('tdp-state');render();stage('availability')};render();