(() => {
  const css=document.createElement('style');css.textContent=`
    .booked-home-link{display:flex;justify-content:center;padding:2px 0 15px}.booked-home-link button{border:0;background:transparent;color:#f3f6f4;font-size:12px;font-weight:950;letter-spacing:.18em;padding:9px 18px;opacity:.9}.booked-home-link button.active{color:#72df9e}
    .booked-event-strip{display:none;border:1px solid #28312d;background:linear-gradient(135deg,#121a16,#0d1114);border-radius:18px;padding:14px 16px;margin:0 0 10px}.booked-event-strip.show{display:flex;align-items:center;justify-content:space-between;gap:14px}.booked-event-strip .event-copy{min-width:0}.booked-event-strip .event-kicker{display:block;color:#70db9b;font-size:9px;font-weight:950;letter-spacing:.15em;margin-bottom:3px}.booked-event-strip strong{display:block;font-size:18px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.booked-event-strip .event-meta{font-size:11px;color:#8f9aa5;margin-top:3px}.booked-event-strip .event-count{text-align:right;font-size:12px;font-weight:900;color:#dce5df;white-space:nowrap}
    .trip-tabs.booked-nav{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;overflow:visible;padding:0 0 15px;margin:0}.trip-tabs.booked-nav .trip-tab{width:100%;padding:10px 8px;text-align:center}
    .trip-status-box{position:sticky;top:10px;z-index:5;margin:14px 0 18px;border:1px solid #33453a;background:rgba(18,28,22,.96);backdrop-filter:blur(12px);border-radius:18px;padding:14px 15px;box-shadow:0 12px 32px rgba(0,0,0,.22)}.trip-status-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:9px}.trip-status-head strong{font-size:12px;letter-spacing:.12em}.trip-status-head span{font-size:10px;color:#76df9f;font-weight:900}.trip-status-list{display:grid;gap:7px}.trip-status-item{display:flex;align-items:flex-start;gap:9px;font-size:12px;color:#cbd4ce}.trip-status-check{width:17px;height:17px;border-radius:5px;border:1px solid #536159;display:grid;place-items:center;flex:none;font-size:11px;margin-top:1px}.trip-status-item.done{color:#7f8d84}.trip-status-item.done .trip-status-check{background:#1d3a29;border-color:#3c7651;color:#78e5a4}.trip-status-item.todo .trip-status-check{background:#151a17}.trip-status-note{margin-top:9px;padding-top:9px;border-top:1px solid #2a352e;color:#8e9b92;font-size:10px}.booked-bingo-placeholder{border:1px dashed #364039;border-radius:20px;padding:28px 20px;text-align:center;color:#8f9aa5}.booked-bingo-placeholder h2{color:#fff;margin:5px 0 7px}
    @media(max-width:620px){.booked-event-strip{padding:12px 13px}.booked-event-strip strong{font-size:16px}.booked-event-strip .event-count{font-size:11px}.trip-status-box{top:8px}}
  `;document.head.appendChild(css);

  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const eventNow=()=>Array.isArray(window.events||events)?(window.events||events).find(e=>e.id===state?.confirmedEventId):null;
  const bookedCrew=()=>{const ids=new Set(((state?.bookings)||[]).filter(b=>b.event_id===state?.confirmedEventId&&(b.attendance_status||'booked')==='booked').map(b=>b.member_id));return (state?.members||[]).filter(m=>ids.has(m.id))};
  const detailsRows=()=>((state?.tripDetails)||[]).filter(r=>r.event_id===state?.confirmedEventId);
  function dateLabel(e){return new Date(e.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}
  function countdown(e){const target=new Date(e.date+'T07:00:00'),diff=target-new Date();if(diff<=0)return 'TRACK DAY';const mins=Math.floor(diff/60000),d=Math.floor(mins/1440),h=Math.floor((mins%1440)/60);return d?`${d}d ${h}h`:`${h}h`}
  function statusHtml(){const crew=bookedCrew(),rows=detailsRows(),done=crew.filter(m=>rows.some(r=>r.member_id===m.id)).length,a=state?.accommodation||{},accom=!!(a.location||a.address||a.stay_details),trailers=rows.filter(r=>r.trailer).length,parking=trailers===0||!!a.parking_notes;const items=[
    {done:done===crew.length&&crew.length>0,text:done===crew.length?'Everyone has completed Trip details':`${crew.length-done} driver${crew.length-done===1?'':'s'} still to complete Trip details`},
    {done:accom,text:accom?'Accommodation confirmed':'Accommodation still to sort'},
    ...(trailers?[{done:parking,text:parking?`Trailer parking noted for ${trailers} trailer${trailers===1?'':'s'}`:`${trailers} trailer${trailers===1?'':'s'} coming — parking needs confirming`}]:[])
  ];const left=items.filter(i=>!i.done).length;return `<section class="trip-status-box"><div class="trip-status-head"><strong>TRIP CHECK</strong><span>${left?`${left} LEFT TO SORT`:'ALL SORTED ✓'}</span></div><div class="trip-status-list">${items.map(i=>`<div class="trip-status-item ${i.done?'done':'todo'}"><span class="trip-status-check">${i.done?'✓':''}</span><span>${esc(i.text)}</span></div>`).join('')}</div><div class="trip-status-note">If Trip details change, the checklist updates automatically for everyone.</div></section>`}
  function refine(shell){if(!shell||shell.dataset.bookedLayout==='1')return;shell.dataset.bookedLayout='1';const e=eventNow();if(!e)return;
    const brand=shell.querySelector('.trip-mode-brand');if(!brand)return;
    const oldNav=shell.querySelector('.trip-tabs');const homePanel=shell.querySelector('[data-trip-panel="home"]'),tripPanel=shell.querySelector('[data-trip-panel="my-trip"]'),stayPanel=shell.querySelector('[data-trip-panel="stay"]');if(!oldNav||!homePanel||!tripPanel||!stayPanel)return;
    oldNav.remove();
    const home=document.createElement('div');home.className='booked-home-link';home.innerHTML='<button type="button" data-booked-home>HOME</button>';brand.after(home);
    const strip=document.createElement('section');strip.className='booked-event-strip';strip.innerHTML=`<div class="event-copy"><span class="event-kicker">CONFIRMED EVENT</span><strong>${esc(e.track)}</strong><div class="event-meta">${esc(dateLabel(e))} · ${esc(e.provider||'Provider TBC')}</div></div><div class="event-count">${esc(countdown(e))}</div>`;home.after(strip);
    const nav=document.createElement('nav');nav.className='trip-tabs booked-nav';nav.innerHTML='<button class="trip-tab" data-booked-tab="trip">Trip</button><button class="trip-tab" data-booked-tab="stay">Stay</button><button class="trip-tab" data-booked-tab="bingo">Bingo</button>';strip.after(nav);
    tripPanel.dataset.tripPanel='trip';
    const bingo=document.createElement('div');bingo.className='trip-panel';bingo.dataset.tripPanel='bingo';bingo.hidden=true;bingo.innerHTML='<section class="booked-bingo-placeholder"><span class="eyebrow">TRACK DAY BINGO</span><h2>Bingo</h2><p>Ready for us to build next.</p></section>';stayPanel.after(bingo);
    homePanel.insertAdjacentHTML('afterbegin',statusHtml());
    const panels={home:homePanel,trip:tripPanel,stay:stayPanel,bingo};const homeBtn=home.querySelector('[data-booked-home]'),tabs=[...nav.querySelectorAll('[data-booked-tab]')];
    const show=id=>{Object.entries(panels).forEach(([key,p])=>p.hidden=key!==id);homeBtn.classList.toggle('active',id==='home');tabs.forEach(t=>t.classList.toggle('active',t.dataset.bookedTab===id));strip.classList.toggle('show',id!=='home');nav.style.display=id==='home'?'grid':'grid';};
    homeBtn.onclick=()=>show('home');tabs.forEach(t=>t.onclick=()=>show(t.dataset.bookedTab));show('home');
  }
  const run=()=>document.querySelectorAll('.trip-mode-shell').forEach(refine);run();new MutationObserver(run).observe(document.body,{childList:true,subtree:true});
})();