(()=>{
const API='https://uehmbzwnbariqebbxcst.supabase.co/functions/v1/trip-track-day';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function creds(action){const pt=localStorage.getItem('tdhParticipantToken');if(pt)return {action,participantToken:pt};try{if(typeof session!=='undefined'&&typeof state!=='undefined'&&session?.groupId&&session?.memberToken&&state?.confirmedEventId)return {action,groupId:session.groupId,token:session.memberToken,eventId:state.confirmedEventId}}catch{}return null}
async function call(action,extra={}){const c=creds(action);if(!c)throw Error('Trip access unavailable');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...c,...extra})}),j=await r.json();if(!r.ok)throw Error(j.error||'Trip Legend unavailable');return j}
const css=document.createElement('style');css.textContent=`
.tdh-legend-card{margin-top:18px;padding:18px;border:1px solid #3b4b42;border-radius:18px;background:radial-gradient(circle at 100% 0,rgba(112,219,155,.09),transparent 40%),#101713;color:#eef5f0}.tdh-legend-kicker{color:#72df9e;font-size:10px;font-weight:950;letter-spacing:.17em}.tdh-legend-card h2{margin:7px 0 6px;font-size:25px}.tdh-legend-muted{color:#929d96;font-size:12px;line-height:1.5}.tdh-legend-slots{display:grid;gap:11px;margin-top:15px}.tdh-legend-slot{padding:14px;border:1px solid #2e3b34;border-radius:14px;background:#0c120f}.tdh-legend-slot label{display:block;margin:0 0 7px;color:#9ca8a1;font-size:10px;font-weight:900;letter-spacing:.1em}.tdh-legend-slot select,.tdh-legend-slot textarea{width:100%;box-sizing:border-box;border:1px solid #39483f;border-radius:10px;background:#080d0a;color:#eef5f0;padding:11px;font:inherit}.tdh-legend-slot textarea{min-height:76px;resize:vertical;margin-top:8px}.tdh-legend-actions{display:flex;gap:8px;margin-top:9px}.tdh-legend-actions button{border:1px solid #3c5748;border-radius:999px;background:#15231b;color:#eef5f0;padding:9px 12px;font-weight:900}.tdh-legend-actions .save{background:#55f08c;color:#07130c;border-color:#55f08c}.tdh-legend-saved{font-size:13px;line-height:1.45}.tdh-legend-saved strong{font-size:16px}.tdh-legend-close{margin-top:12px;color:#7f8c84;font-size:10px}.tdh-legend-error{padding:13px;color:#ffb4a8}
`;document.head.appendChild(css);
function closeText(j){if(!j.closesAt)return'';return 'Nominations close '+new Date(j.closesAt).toLocaleString('en-GB',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}
async function render(host,{compact=false}={}){if(!host)return;host.innerHTML='<section class="tdh-legend-card"><div class="tdh-legend-kicker">TRIP LEGEND 🏆</div><p class="tdh-legend-muted">Loading nominations…</p></section>';try{const j=await call('legend-status');const mine=new Map((j.myNominations||[]).map(x=>[Number(x.slot),x]));host.innerHTML=`<section class="tdh-legend-card"><div class="tdh-legend-kicker">TRIP LEGEND 🏆</div><h2>Who deserves it?</h2><div class="tdh-legend-muted">You get two nominations for the whole Trip. Pick a Trip participant and tell the story. You can nominate the same person twice for two genuinely different reasons. Nobody sees who nominated them.</div><div class="tdh-legend-slots">${[1,2].map(slot=>{const n=mine.get(slot);if(n)return `<div class="tdh-legend-slot" data-slot="${slot}"><label>NOMINATION ${slot}</label><div class="tdh-legend-saved"><strong>${esc(n.nominee_name)}</strong><div>${esc(n.reason)}</div></div>${j.open?`<div class="tdh-legend-actions"><button data-edit>Edit</button><button data-delete>Remove</button></div>`:''}</div>`;return `<div class="tdh-legend-slot" data-slot="${slot}"><label>NOMINATION ${slot}</label>${j.open?`<select data-person><option value="">Choose Trip participant…</option>${j.eligible.map(p=>`<option value="${esc(p.type+':'+p.id)}">${esc(p.name)}</option>`).join('')}</select><textarea data-reason placeholder="Why are they Trip Legend-worthy?"></textarea><div class="tdh-legend-actions"><button class="save" data-save>Save nomination</button></div>`:'<div class="tdh-legend-muted">Nominations are closed.</div>'}</div>`}).join('')}</div><div class="tdh-legend-close">${esc(closeText(j))}</div></section>`;
host.querySelectorAll('[data-slot]').forEach(box=>{const slot=Number(box.dataset.slot);box.querySelector('[data-edit]')?.addEventListener('click',()=>{const n=mine.get(slot);box.innerHTML=`<label>NOMINATION ${slot}</label><select data-person><option value="">Choose Trip participant…</option>${j.eligible.map(p=>`<option value="${esc(p.type+':'+p.id)}" ${(p.type===String(n.nominee_type||'member')&&String(p.id)===String(n.nominee_id||n.nominee_member_id))?'selected':''}>${esc(p.name)}</option>`).join('')}</select><textarea data-reason>${esc(n.reason)}</textarea><div class="tdh-legend-actions"><button class="save" data-save>Save changes</button></div>`;wire(box,slot,host)});box.querySelector('[data-delete]')?.addEventListener('click',async()=>{if(!confirm('Remove this Trip Legend nomination?'))return;try{await call('legend-delete',{slot});await render(host,{compact})}catch(e){alert(e.message)}});wire(box,slot,host)});return j}catch(e){host.innerHTML=`<section class="tdh-legend-card"><div class="tdh-legend-kicker">TRIP LEGEND 🏆</div><div class="tdh-legend-error">${esc(e.message)}</div></section>`}}
function wire(box,slot,host){const b=box.querySelector('[data-save]');if(!b||b.dataset.wired)return;b.dataset.wired='1';b.onclick=async()=>{const nomineeValue=box.querySelector('[data-person]')?.value||'',sep=nomineeValue.indexOf(':'),nomineeType=sep>0?nomineeValue.slice(0,sep):'member',nomineeId=sep>0?nomineeValue.slice(sep+1):nomineeValue,reason=box.querySelector('[data-reason]')?.value.trim();if(!nomineeId)return alert('Choose a Trip participant.');if(!reason)return alert('Tell us why they deserve the nomination.');b.disabled=true;try{await call('legend-nominate',{slot,nomineeType,nomineeId,reason});await render(host)}catch(e){alert(e.message);b.disabled=false}}}
window.TDHTripLegend={render};window.TDHCrewLegend=window.TDHTripLegend;
})();