(()=>{
  const pad2=n=>String(n).padStart(2,'0');
  function fromSeconds(n){n=Number(n);if(!Number.isFinite(n)||n<=0)return null;const total=Math.round(n*100),min=Math.floor(total/6000),rem=total-min*6000,sec=Math.floor(rem/100),hundredths=rem%100;return {milliseconds:total*10,display:`${min}:${pad2(sec)}.${pad2(hundredths)}`};}
  function parseLapTime(value){let s=String(value??'').trim().replace(/,/g,'.');if(!s)return null;s=s.replace(/\s+/g,':');let min=0,sec=0;if(s.includes(':')){const p=s.split(':').filter(Boolean);if(p.length>2)return null;min=Number(p.length===2?p[0]:0);sec=Number(p.length===2?p[1]:p[0]);}else{const dots=(s.match(/\./g)||[]).length;if(dots>=2){const p=s.split('.');min=Number(p.shift());sec=Number(p.shift()+'.'+p.join(''));}else{const n=Number(s);if(!Number.isFinite(n))return null;if(n>=60){min=Math.floor(n/60);sec=n-min*60}else sec=n;}}if(!Number.isFinite(min)||!Number.isFinite(sec)||min<0||sec<0||sec>=60)return null;return fromSeconds(min*60+sec);}
  function detectDelimiter(line){const counts=[[';',line.split(';').length],['\t',line.split('\t').length],[',',line.split(',').length]];counts.sort((a,b)=>b[1]-a[1]);return counts[0][1]>1?counts[0][0]:',';}
  function csvRows(text){text=String(text||'');const first=(text.split(/\r?\n/).find(Boolean)||''),delimiter=detectDelimiter(first),rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted;}else if(!quoted&&c===delimiter){row.push(cell.trim());cell='';}else if(!quoted&&(c==='\n'||c==='\r')){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell.trim());cell='';if(row.some(Boolean))rows.push(row);row=[];}else cell+=c;}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows;}
  function parseLapTrophyCSV(text){const rows=csvRows(text);if(rows.length<2)return [];const header=rows[0].map(x=>String(x).trim().toLowerCase());let timeIdx=header.findIndex(h=>h==='time (s)'||h==='time(s)'||h==='lap time (s)'||h==='lap time');if(timeIdx<0)timeIdx=header.findIndex(h=>/^time\s*\(?(?:s|sec|seconds)\)?$/.test(h));if(timeIdx<0)return [];const sessionIdx=header.findIndex(h=>h==='session date'||h==='session start'||h==='session');const lapIdx=header.findIndex(h=>h==='lap index'||h==='lap'||h==='lap number');const secondsColumn=/\((?:s|sec|seconds)\)|\bseconds?\b/.test(header[timeIdx]);const sessions=new Map();for(let r=1;r<rows.length;r++){const raw=rows[r][timeIdx];if(raw==null||String(raw).trim()==='')continue;const parsed=secondsColumn?fromSeconds(String(raw).trim().replace(',','.')):parseLapTime(raw);if(!parsed||parsed.milliseconds<10000)continue;const session=sessionIdx>=0?(rows[r][sessionIdx]||'Session'):'Session';const lapNumber=lapIdx>=0?rows[r][lapIdx]:'';const item={time:parsed.display,milliseconds:parsed.milliseconds,raw,row:r+1,session,lapNumber};const existing=sessions.get(session);if(!existing)sessions.set(session,{session,lapCount:1,fastest:item});else{existing.lapCount++;if(item.milliseconds<existing.fastest.milliseconds)existing.fastest=item;}}
    return Array.from(sessions.values()).map((s,i)=>({...s.fastest,session:s.session,sessionNumber:i+1,lapCount:s.lapCount}));
  }
  window.TDHLaps={parseLapTime,parseLapTrophyCSV};

  if(/passenger\.html$/i.test(location.pathname)){
    const style=document.createElement('style');style.textContent=`.passenger-trip-hero{position:relative;overflow:hidden;min-height:300px;padding:30px;box-sizing:border-box;border-radius:28px;background:linear-gradient(135deg,#1c2228,#0c0f13);margin:16px 0 20px}.passenger-trip-hero .kicker{font-size:10px;font-weight:900;letter-spacing:.16em;color:#70db9b}.passenger-trip-hero h1{font-size:clamp(45px,10vw,82px);line-height:.9;margin:14px 0 17px;text-transform:uppercase}.passenger-trip-hero .date{color:#cbd3dc}.passenger-trip-hero .countdown{display:inline-flex;flex-direction:column;margin-top:42px;font-size:clamp(34px,8vw,58px);font-weight:950}.passenger-trip-hero .countdown span{font-size:10px;letter-spacing:.2em;color:#78838f}@media(max-width:620px){.passenger-trip-hero{padding:24px 20px}}`;document.head.appendChild(style);
    const originalFetch=window.fetch.bind(window);window.fetch=async(...args)=>{const response=await originalFetch(...args);try{const url=String(args[0]||'');if(url.includes('action=participant')){const data=await response.clone().json(),p=data.participant||{},eventId=String(p.event_id||data.event_id||''),m=eventId.match(/^(.*)-(\d{4}-\d{2}-\d{2})-(.+)$/),date=p.event_date||p.date||data.event_date||(m&&m[2])||'',track=p.track_name||data.track_name||(m?m[3].split('-').filter(Boolean).map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(' '):'Track Day'),provider=p.provider||p.event_provider||data.provider||(m?m[1]:'');setTimeout(()=>renderPassengerHero({date,track,provider}),0)}}catch{}return response};
    function countdown(date){if(!date)return 'COUNTDOWN';const diff=new Date(date+'T07:00:00')-new Date();if(diff<=0)return 'TRACK DAY';const mins=Math.floor(diff/60000),days=Math.floor(mins/1440),hours=Math.floor((mins%1440)/60),minutes=mins%60;return days>0?`${days}d ${hours}h ${minutes}m`:`${hours}h ${minutes}m`}
    function renderPassengerHero(e){const home=document.querySelector('[data-panel="home"]');if(!home)return setTimeout(()=>renderPassengerHero(e),50);home.querySelector('.passenger-trip-hero')?.remove();const dateLabel=e.date?new Date(e.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'';const hero=document.createElement('section');hero.className='passenger-trip-hero';hero.innerHTML=`<span class="kicker">THE NEXT ONE</span><h1>${String(e.track).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</h1><p class="date">${dateLabel}${e.provider?' · '+e.provider:''}</p><div class="countdown">${countdown(e.date)}<span>UNTIL WE’RE ON TRACK</span></div>`;home.insertBefore(hero,home.firstChild);setInterval(()=>{const el=hero.querySelector('.countdown');if(el)el.innerHTML=`${countdown(e.date)}<span>UNTIL WE’RE ON TRACK</span>`},30000)}
  }
})();