(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const css=document.createElement('style');css.textContent=`
 #tdhMasterHome{position:fixed;inset:0;z-index:100150;overflow:auto;background:#080b0d;color:#eef5f0;padding:calc(env(safe-area-inset-top) + 18px) 16px calc(env(safe-area-inset-bottom) + 28px);font-family:system-ui,-apple-system,sans-serif}
 .tdh-home-wrap{max-width:760px;margin:auto}.tdh-home-brand{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:4px 0 24px}.tdh-home-brand small{display:block;color:#72df9e;font-size:10px;font-weight:950;letter-spacing:.17em}.tdh-home-brand h1{font-size:25px;margin:4px 0 0}
 .tdh-home-card{border:1px solid #2c3a33;border-radius:20px;background:#101619;padding:16px;margin:0 0 14px}.tdh-home-card>small{display:block;color:#72df9e;font-size:10px;font-weight:950;letter-spacing:.16em;margin-bottom:11px}.tdh-me{display:flex;align-items:center;justify-content:space-between;gap:12px}.tdh-me h2{margin:0;font-size:23px}.tdh-me p{margin:4px 0 0;color:#9ba8a0}.tdh-home-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.tdh-home-actions button{border:1px solid #3e5c4b;border-radius:12px;background:#17221c;color:#edf5f0;padding:10px 13px;font-weight:900}.tdh-home-actions .primary{border-color:#72df9e;background:#72df9e;color:#07130c}
 .tdh-crew-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 2px;border-top:1px solid #26312c}.tdh-crew-row:first-of-type{border-top:0}.tdh-crew-row b{display:block}.tdh-crew-row span{display:block;color:#8f9c94;font-size:12px;margin-top:3px}.tdh-you{color:#72df9e!important;font-size:10px!important;font-weight:900!important;letter-spacing:.1em}
 .tdh-settings-row{padding:13px 2px;border-top:1px solid #26312c;color:#dce5df}.tdh-settings-row:first-of-type{border-top:0}.tdh-settings-row span{float:right;color:#738079}.tdh-home-note{color:#78857d;font-size:11px;line-height:1.45;margin:10px 2px 0}
 `;document.head.appendChild(css);
 function hideOthers(){document.querySelector('#planningV2')?.style.setProperty('display','none','important');const s=document.querySelector('.trip-mode-shell');if(s)s.style.setProperty('display','none','important');window.TDHPreEvent?.close?.();window.TDHResultsHome?.close?.();window.TDHTrackDayMode?.suspend?.();document.getElementById('tdhPostTrack')?.remove()}
 function invite(){const code=state?.group?.invite_code;if(!code)return alert('Crew invite is not available yet.');const url=`${location.origin}${location.pathname}?invite=${encodeURIComponent(code)}`;const text=`Join our crew on Track Day Heros 🏁\n${url}`;if(navigator.share){navigator.share({title:'Track Day Heros',text,url}).catch(e=>{if(e?.name!=='AbortError')prompt('Copy Crew invite',url)})}else navigator.clipboard?.writeText(url).then(()=>alert('Crew invite copied')).catch(()=>prompt('Copy Crew invite',url))}
 async function editProfile(){const me=state?.me;if(!me||!session)return;const name=prompt('Your name',me.name||'');if(name===null)return;const cleanName=name.trim();if(!cleanName)return alert('Please enter your name.');const car=prompt('Your car',me.car||'');if(car===null)return;const cleanCar=car.trim();if(!cleanCar)return alert('Please enter your car.');try{await api('update-profile','POST',{groupId:session.groupId,token:session.memberToken,name:cleanName,car:cleanCar});state=await api('group','GET',{groupId:session.groupId,token:session.memberToken});render();open()}catch(e){alert('Could not update profile: '+(e?.message||e))}}
 function renderHome(){const me=state?.me||{},members=state?.members||[];return `<div class="tdh-home-wrap"><header class="tdh-home-brand"><div><small>TRACK DAY HEROS</small><h1>Home 🏁</h1></div></header><section class="tdh-home-card"><small>MY PROFILE</small><div class="tdh-me"><div><h2>${esc(me.name||'Crew member')}</h2><p>${esc(me.car||'No car added')}</p></div></div><div class="tdh-home-actions"><button type="button" data-home-edit>Edit profile</button></div></section><section class="tdh-home-card"><small>YOUR CREW</small>${members.map(m=>`<div class="tdh-crew-row"><div><b>${esc(m.name||'Crew member')}</b><span>${esc(m.car||'No car added')}</span></div>${m.id===me.id?'<span class="tdh-you">YOU</span>':''}</div>`).join('')||'<p class="tdh-home-note">No Crew members found.</p>'}<div class="tdh-home-actions"><button type="button" class="primary" data-home-invite>+ INVITE CREW</button></div></section><section class="tdh-home-card"><small>SETTINGS</small><div class="tdh-settings-row">Notifications <span>COMING SOON</span></div><div class="tdh-settings-row">Account & group <span>›</span></div><p class="tdh-home-note">Permanent Crew and account settings live here. Trip-specific controls stay with Plan, Travel, Event and Results.</p></section></div>`}
 function open(){hideOthers();let root=document.getElementById('tdhMasterHome');if(!root){root=document.createElement('div');root.id='tdhMasterHome';document.body.appendChild(root)}root.innerHTML=renderHome();root.querySelector('[data-home-edit]')?.addEventListener('click',editProfile);root.querySelector('[data-home-invite]')?.addEventListener('click',invite);window.TDHGlobalNav?.refresh?.();window.scrollTo(0,0)}
 function close(){document.getElementById('tdhMasterHome')?.remove()}
 window.TDHMasterHome={open,close};
})();