(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const avatar=(m,size=54)=>window.tdpAvatarHTML?window.tdpAvatarHTML(m,size,false):`<span class="tdh-home-initial" style="width:${size}px;height:${size}px">${esc((m?.name||'?').charAt(0).toUpperCase())}</span>`;
 const css=document.createElement('style');css.textContent=`
 #tdhMasterHome{position:fixed;inset:0;z-index:100150;overflow:auto;background:#080b0d;color:#eef5f0;padding:calc(env(safe-area-inset-top) + 18px) 16px calc(env(safe-area-inset-bottom) + 28px);font-family:system-ui,-apple-system,sans-serif}
 .tdh-home-wrap{max-width:760px;margin:auto}.tdh-home-brand{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:4px 0 24px}.tdh-home-brand small,.tdh-home-card>small,.tdh-profile-label{display:block;color:#72df9e;font-size:10px;font-weight:950;letter-spacing:.17em}.tdh-home-brand h1{font-size:25px;margin:4px 0 0}
 .tdh-home-card{border:1px solid #2c3a33;border-radius:20px;background:#101619;padding:16px;margin:0 0 14px}.tdh-home-card>small{margin-bottom:11px}
 .tdh-profile-view{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:14px}.tdh-profile-copy h2{margin:0;font-size:23px}.tdh-profile-copy p{margin:4px 0 0;color:#9ba8a0}.tdh-profile-edit{border:1px solid #3e5c4b;border-radius:12px;background:#17221c;color:#edf5f0;padding:10px 13px;font-weight:900}
 .tdh-profile-form{display:grid;gap:13px}.tdh-profile-form label{display:grid;gap:6px;color:#9ba8a0;font-size:11px;font-weight:900;letter-spacing:.08em}.tdh-profile-form input{width:100%;box-sizing:border-box;border:1px solid #344139;border-radius:13px;background:#090e10;color:#eef5f0;padding:13px 14px;font:inherit;font-size:16px}.tdh-avatar-pick{display:flex;align-items:center;gap:13px;border:1px solid #344139;border-radius:15px;background:#0c1214;padding:11px;color:#eef5f0;text-align:left}.tdh-avatar-pick strong{display:block}.tdh-avatar-pick span{color:#8f9c94;font-size:11px}.tdh-profile-buttons{display:grid;grid-template-columns:1fr 1fr;gap:9px}.tdh-profile-buttons button,.tdh-home-actions button{border:1px solid #3e5c4b;border-radius:12px;background:#17221c;color:#edf5f0;padding:11px 13px;font-weight:900}.tdh-profile-buttons .primary,.tdh-home-actions .primary{border-color:#72df9e;background:#72df9e;color:#07130c}
 .tdh-home-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.tdh-crew-row{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:12px;padding:12px 2px;border-top:1px solid #26312c}.tdh-crew-row:first-of-type{border-top:0}.tdh-crew-row b{display:block}.tdh-crew-row .tdh-car{display:block;color:#8f9c94;font-size:12px;margin-top:3px}.tdh-you{color:#72df9e!important;font-size:10px!important;font-weight:900!important;letter-spacing:.1em}.tdh-home-initial{display:inline-flex;align-items:center;justify-content:center;border-radius:50%;background:#2b313a;border:2px solid #707985;box-sizing:border-box;font-weight:900}
 .tdh-settings-row{padding:13px 2px;border-top:1px solid #26312c;color:#dce5df}.tdh-settings-row:first-of-type{border-top:0}.tdh-settings-row span{float:right;color:#738079}.tdh-home-note{color:#78857d;font-size:11px;line-height:1.45;margin:10px 2px 0}
 @media(max-width:520px){.tdh-profile-view{grid-template-columns:auto 1fr}.tdh-profile-edit{grid-column:1/-1;width:max-content}.tdh-home-card{padding:16px}}
 `;document.head.appendChild(css);
 let editing=false;
 function hideOthers(){document.querySelector('#planningV2')?.style.setProperty('display','none','important');const s=document.querySelector('.trip-mode-shell');if(s)s.style.setProperty('display','none','important');window.TDHPreEvent?.close?.();window.TDHResultsHome?.close?.();window.TDHTrackDayMode?.suspend?.();document.getElementById('tdhPostTrack')?.remove()}
 function invite(){const code=state?.group?.invite_code;if(!code)return alert('Crew invite is not available yet.');const url=`${location.origin}${location.pathname}?invite=${encodeURIComponent(code)}`;const text=`Join our crew on Track Day Heros 🏁\n${url}`;if(navigator.share){navigator.share({title:'Track Day Heros',text,url}).catch(e=>{if(e?.name!=='AbortError')prompt('Copy Crew invite',url)})}else navigator.clipboard?.writeText(url).then(()=>alert('Crew invite copied')).catch(()=>prompt('Copy Crew invite',url))}
 async function saveProfile(root){const me=state?.me;if(!me||!session)return;const name=root.querySelector('[data-profile-name]')?.value.trim(),car=root.querySelector('[data-profile-car]')?.value.trim();if(!name)return alert('Please enter your name.');if(!car)return alert('Please enter your car.');const btn=root.querySelector('[data-profile-save]');if(btn){btn.disabled=true;btn.textContent='Saving…'}try{await api('update-profile','POST',{groupId:session.groupId,token:session.memberToken,name,car});state=await api('group','GET',{groupId:session.groupId,token:session.memberToken});editing=false;open()}catch(e){alert('Could not update profile: '+(e?.message||e));if(btn){btn.disabled=false;btn.textContent='Save changes'}}}
 function renderProfile(me){if(!editing)return `<div class="tdh-profile-view">${avatar(me,64)}<div class="tdh-profile-copy"><h2>${esc(me.name||'Crew member')}</h2><p>${esc(me.car||'No car added')}</p></div><button type="button" class="tdh-profile-edit" data-home-edit>Edit profile</button></div>`;return `<div class="tdh-profile-form"><button type="button" class="tdh-avatar-pick" data-home-avatar>${avatar(me,64)}<div><strong>Choose avatar</strong><span>${me.avatar?'Tap to change your current avatar':'Add your Crew character'}</span></div></button><label>YOUR NAME<input data-profile-name value="${esc(me.name||'')}" autocomplete="name"></label><label>YOUR CAR<input data-profile-car value="${esc(me.car||'')}" autocomplete="off"></label><div class="tdh-profile-buttons"><button type="button" data-profile-cancel>Cancel</button><button type="button" class="primary" data-profile-save>Save changes</button></div></div>`}
 function renderHome(){const me=state?.me||{},members=state?.members||[];return `<div class="tdh-home-wrap"><header class="tdh-home-brand"><div><small>TRACK DAY HEROS</small><h1>Home 🏁</h1></div></header><section class="tdh-home-card"><small>MY PROFILE</small>${renderProfile(me)}</section><section class="tdh-home-card"><small>YOUR CREW</small>${members.map(m=>`<div class="tdh-crew-row">${avatar(m,44)}<div><b>${esc(m.name||'Crew member')}</b><span class="tdh-car">${esc(m.car||'No car added')}</span></div>${m.id===me.id?'<span class="tdh-you">YOU</span>':''}</div>`).join('')||'<p class="tdh-home-note">No Crew members found.</p>'}<div class="tdh-home-actions"><button type="button" class="primary" data-home-invite>+ INVITE CREW</button></div></section><section class="tdh-home-card"><small>SETTINGS</small><div class="tdh-settings-row">Notifications <span>COMING SOON</span></div><div class="tdh-settings-row">Account & group <span>›</span></div><p class="tdh-home-note">Permanent Crew and account settings live here. Trip-specific controls stay with Plan, Travel, Event and Results.</p></section></div>`}
 function wire(root){root.querySelector('[data-home-edit]')?.addEventListener('click',()=>{editing=true;open()});root.querySelector('[data-profile-cancel]')?.addEventListener('click',()=>{editing=false;open()});root.querySelector('[data-profile-save]')?.addEventListener('click',()=>saveProfile(root));root.querySelector('[data-home-avatar]')?.addEventListener('click',()=>window.openAvatarPicker?.());root.querySelector('[data-home-invite]')?.addEventListener('click',invite)}
 function open(){hideOthers();let root=document.getElementById('tdhMasterHome');if(!root){root=document.createElement('div');root.id='tdhMasterHome';document.body.appendChild(root)}root.innerHTML=renderHome();wire(root);window.TDHGlobalNav?.refresh?.();window.scrollTo(0,0)}
 function close(){editing=false;document.getElementById('tdhMasterHome')?.remove()}
 window.TDHMasterHome={open,close};
})();