(()=>{
 const ENDPOINT='https://uehmbzwnbariqebbxcst.supabase.co/functions/v1/trip-bingo';
 const CATS=[['engine_cooling','Engine / Cooling'],['gearbox_drivetrain','Gearbox / Drivetrain'],['brakes','Brakes'],['suspension_steering','Suspension / Steering'],['tyre_wheel','Tyre / Wheel'],['electrical_bodywork_aero','Electrical / Bodywork / Aero'],['fuel','Fuel'],['driver_error','Driver Error 😂']];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const catLabel=v=>CATS.find(x=>x[0]===v)?.[1]||v||'';
 let ctx=null,bingo=null,loading=false;
 const token=()=>localStorage.getItem('tdhParticipantToken')||'';
 async function req(method='GET',payload={}){const t=token();if(!t)return null;if(method==='GET'){const q=new URLSearchParams({action:'passenger-status',participantToken:t});const r=await fetch(`${ENDPOINT}?${q}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not load Bingo');return j}const r=await fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({participantToken:t,...payload})}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not update Bingo');return j}
 function panel(){return document.querySelector('[data-panel="bingo"]')}
 async function load(){if(loading||!ctx)return;loading=true;try{bingo=await req();render()}catch(e){const p=panel();if(p)p.innerHTML=`<h2>Broken Car Bingo</h2><div class="bingo-box">${esc(e.message)}</div>`}finally{loading=false}}
 function render(){const p=panel();if(!p||!bingo)return;const pred=bingo.prediction,cars=bingo.subjects||[],tim=bingo.timing||{};if(!bingo.unlocked){p.innerHTML='<h2>Broken Car Bingo</h2><div class="bingo-box">Bingo is still locked while the Crew sorts the trip details.</div>';return}if(tim.locked){p.innerHTML=`<h2>Broken Car Bingo</h2><div class="bingo-box"><b>Prediction locked 🔒</b><br><br>${pred?`You picked <b>${esc(pred.subject_car)}</b> — ${esc(pred.predicted_failure)}<br><span class="muted">${esc(catLabel(pred.defect_category))}</span><br><br>It stays secret until the post-track Results game.`:'No prediction was entered before the 19:00 lock.'}</div>`;return}p.innerHTML=`<h2>Broken Car Bingo</h2><div class="info"><b>🤫 One shot. Completely secret.</b><br><span class="muted">Choose a car, say exactly what you reckon will happen, then pick the category that best matches it.</span></div><div class="field"><label>CHOOSE CAR</label><select id="pBingoCar"><option value="">Choose your victim…</option>${cars.map(c=>`<option value="${esc(c.member_id)}" ${pred?.subject_member_id===c.member_id?'selected':''}>${esc(c.driver_name||'Hero')} — ${esc(c.car_snapshot||c.car||'')}</option>`).join('')}</select></div><div class="field"><label>WHAT DO YOU RECKON WILL HAPPEN?</label><input id="pBingoFailure" maxlength="120" value="${esc(pred?.predicted_failure||'')}" placeholder="NSF driveshaft lets go at Quarry 😂"></div><div class="field"><label>PROBLEM CATEGORY</label><select id="pBingoCategory"><option value="">Best match…</option>${CATS.map(([v,l])=>`<option value="${v}" ${pred?.defect_category===v?'selected':''}>${l}</option>`).join('')}</select></div><button id="pBingoSave" class="primary">${pred?'CHANGE PREDICTION':'LOCK IN PREDICTION'} 🎯</button>${pred?'<p class="import-status">Prediction saved ✓ · still secret</p>':''}`;document.getElementById('pBingoSave').onclick=save}
 async function save(){const subject=document.getElementById('pBingoCar')?.value,failure=document.getElementById('pBingoFailure')?.value.trim(),defectCategory=document.getElementById('pBingoCategory')?.value;if(!subject||!failure||!defectCategory)return alert('Choose a car, describe the problem and pick its category 😁');const b=document.getElementById('pBingoSave');b.disabled=true;try{await req('POST',{action:'passenger-save-prediction',subjectMemberId:subject,predictedFailure:failure,defectCategory});bingo=null;await load()}catch(e){alert(e.message);b.disabled=false}}
 function loadTrackDayMode(){if(!document.querySelector('script[src^="/track-day-mode.js"]')){const t=document.createElement('script');t.src='/track-day-mode.js?v=20260921-passengerlaps';document.body.appendChild(t)}}
 window.addEventListener('tdh-passenger-loaded',e=>{ctx=e.detail;load();loadTrackDayMode()});document.addEventListener('click',e=>{if(e.target.closest('[data-tab="bingo"]'))setTimeout(load,20)});
})();