(()=>{
const API='https://uehmbzwnbariqebbxcst.supabase.co/functions/v1/trip-track-day';
const CATS=[['engine_cooling','Engine / Cooling'],['gearbox_drivetrain','Gearbox / Drivetrain'],['brakes','Brakes'],['suspension_steering','Suspension / Steering'],['tyre_wheel','Tyre / Wheel'],['electrical_bodywork_aero','Electrical / Bodywork / Aero'],['fuel','Fuel'],['driver_error','Driver Error 😂']];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const creds=()=>{const pt=localStorage.getItem('tdhParticipantToken');if(pt)return{participantToken:pt};try{if(session?.groupId&&session?.memberToken&&state?.confirmedEventId)return{groupId:session.groupId,token:session.memberToken,eventId:state.confirmedEventId}}catch{}return{}};
async function call(action,body){const c=creds(),r=await fetch(API,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...c,...body})}:{cache:'no-store'});let rr=r;if(!body)rr=await fetch(API+'?'+new URLSearchParams({action,...c}),{cache:'no-store'});const j=await rr.json();if(!rr.ok)throw Error(j.error||'Event unavailable');return j}
function eventName(){try{const id=state?.confirmedEventId||'';const after=id.replace(/^.*?\d{4}-\d{2}-\d{2}-/,'');return after?after.split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' '):'Next Track Day'}catch{return'Next Track Day'}}
function shell(){let r=document.getElementById('tdhPreEvent');if(!r){r=document.createElement('div');r.id='tdhPreEvent';document.body.appendChild(r)}return r}
const css=document.createElement('style');css.textContent=`#tdhPreEvent{position:fixed;inset:0;z-index:100005;overflow:auto;background:#080b0d;color:#eef5f0;font-family:system-ui,-apple-system,sans-serif}.tdh-pe-wrap{max-width:720px;margin:auto;padding:22px 18px 70px}.tdh-pe-brand{display:flex;align-items:center;justify-content:space-between;gap:12px;font-weight:900}.tdh-pe-hero{padding:52px 0 24px}.tdh-pe-kicker{color:#55f08c;font-size:10px;font-weight:950;letter-spacing:.2em}.tdh-pe-hero h1{font-size:46px;line-height:.94;font-style:italic;text-transform:uppercase;margin:10px 0}.tdh-pe-date{font-size:17px;font-weight:850}.tdh-pe-count{margin-top:22px;font-size:13px;color:#9aa6ad}.tdh-pe-card{background:#10161a;border:1px solid #29333a;border-radius:19px;padding:18px;margin:12px 0}.tdh-pe-card h2{margin:5px 0 7px}.tdh-pe-muted{color:#9aa6ad;font-size:13px;line-height:1.5}.tdh-pe-primary{width:100%;min-height:51px;margin-top:14px;border:0;border-radius:999px;background:#55f08c;color:#07130c;font-weight:950}.tdh-pe-field{margin:13px 0}.tdh-pe-field label{display:block;font-size:10px;font-weight:900;letter-spacing:.12em;color:#98a5ad;margin-bottom:7px}.tdh-pe-field select,.tdh-pe-field textarea{width:100%;box-sizing:border-box;border:1px solid #344149;border-radius:13px;background:#090d10;color:#eef5f0;padding:13px;font:inherit}.tdh-pe-field textarea{min-height:88px;resize:vertical}.tdh-pe-log{padding:13px 0;border-bottom:1px solid #273038}.tdh-pe-log:last-child{border-bottom:0}.tdh-pe-log small{display:block;color:#89969e;margin-top:5px}.tdh-pe-empty{color:#89969e;text-align:center;padding:14px}.tdh-pe-note{border-left:2px solid #55f08c;padding-left:12px;margin-top:12px}`;document.head.appendChild(css);
let current=null;
function nonAttending(){try{const row=(state?.bookings||[]).find(b=>b.event_id===state?.confirmedEventId&&b.member_id===state?.me?.id);return !!row&&(row.attendance_status||'')!=='booked'}catch{return false}}
function activityRows(rows,empty,kind){if(!rows?.length)return '<div class="tdh-pe-empty">'+empty+'</div>';return rows.map(x=>kind==='lap'?'<div class="tdh-pe-log"><strong>'+esc(x.time_display||x.lap_time||'Lap')+' · '+esc(x.car_snapshot||'')+'</strong><small>'+esc(x.actor_name||x.driver_name||'Crew')+' · '+esc(x.source||'Lap')+'</small></div>':'<div class="tdh-pe-log"><strong>'+esc(x.driver_name||'Crew')+' — '+esc(x.car_snapshot||'')+'</strong><div>'+esc(x.description||'')+'</div><small>'+new Date(x.created_at).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})+' · Added by '+esc(x.added_by_name||'Crew')+'</small></div>').join('')}
async function paintFollower(){const r=shell(),j=current;let lapData={laps:[]};try{lapData=await call('laps')}catch{}const date=j.eventDate?new Date(j.eventDate+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'';r.innerHTML='<div class="tdh-pe-wrap"><div class="tdh-pe-brand">Track Day Heros 🏁 · EVENT</div><section class="tdh-pe-hero"><div class="tdh-pe-kicker">FOLLOWING THIS EVENT</div><h1>'+esc(eventName())+'</h1><div class="tdh-pe-date">'+esc(date)+'</div><div class="tdh-pe-count">'+esc(countdown(j))+'</div></section><section class="tdh-pe-card"><div class="tdh-pe-kicker">LAPS · VIEW ONLY</div><h2>Track times</h2><div>'+activityRows(lapData.laps||[],'No laps recorded yet.','lap')+'</div></section><section class="tdh-pe-card"><div class="tdh-pe-kicker">BROKEN CAR LOG · VIEW ONLY</div><h2>What happened?</h2><div class="tdh-pe-muted">You can follow the Crew\'s Event activity here, but you cannot add or delete entries while Not Attending.</div><div style="margin-top:12px">'+activityRows(j.logs||[],'Nothing broken yet. Suspicious. 😂','log')+'</div></section></div>';window.TDHGlobalNav?.refresh?.()}
function countdown(j){const d=new Date(j.eventDate+'T09:00:00'),ms=d-Date.now(),days=Math.max(0,Math.ceil(ms/86400000));return ms>0?(days===1?'Tomorrow':days+' days to go'):'Track day is here'}
function paint(){const j=current,r=shell(),date=j.eventDate?new Date(j.eventDate+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'';r.innerHTML=`<div class="tdh-pe-wrap"><div class="tdh-pe-brand">Track Day Heros 🏁 · EVENT</div><section class="tdh-pe-hero"><div class="tdh-pe-kicker">NEXT EVENT</div><h1>${esc(eventName())}</h1><div class="tdh-pe-date">${esc(date)}</div><div class="tdh-pe-count">${esc(countdown(j))}</div></section><section class="tdh-pe-card"><div class="tdh-pe-kicker">BROKEN CAR LOG</div><h2>Problems start counting now. 😬</h2><div class="tdh-pe-muted">The Trip is confirmed, so defects can already be logged for the Trip record and Points. Only Event-window defects can qualify for Bingo.</div><div class="tdh-pe-field"><label>CREW CAR</label><select data-car>${j.cars.map(c=>`<option value="${esc(c.member_id)}">${esc(c.driver_name)} — ${esc(c.car)}</option>`).join('')}</select></div><div class="tdh-pe-field"><label>WHAT HAPPENED?</label><textarea data-desc placeholder="e.g. Car won't start while loading up"></textarea></div><div class="tdh-pe-field"><label>PROBLEM CATEGORY</label><select data-cat><option value="">Best match…</option>${CATS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div><button class="tdh-pe-primary" data-log>LOG IT</button></section><section class="tdh-pe-card"><div class="tdh-pe-kicker">TRIP PROBLEMS</div><div data-logs>${j.logs?.length?j.logs.map(x=>`<div class="tdh-pe-log"><strong>${esc(x.driver_name)}'s ${esc(x.car_snapshot)}</strong><div>${esc(x.description)}</div><small>${new Date(x.created_at).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · Added by ${esc(x.added_by_name)}</small></div>`).join(''):'<div class="tdh-pe-empty">Nothing logged yet. Long may it continue.</div>'}</div></section><section class="tdh-pe-card"><div class="tdh-pe-kicker">ON THE DAY</div><h2>Laps unlock with Track Day Mode.</h2><div class="tdh-pe-muted">At 07:00 on Event day, EVENT hands over to the tested Track Day page. Starting Track Day remains an individual action.</div></section></div>`;r.querySelector('[data-log]').onclick=async e=>{const carMemberId=r.querySelector('[data-car]').value,description=r.querySelector('[data-desc]').value.trim(),defectCategory=r.querySelector('[data-cat]').value;if(!description)return alert('Tell us what happened.');if(!defectCategory)return alert('Pick the problem category that best matches.');e.currentTarget.disabled=true;try{await call('log',{carMemberId,description,defectCategory});current=await call('status');paint()}catch(err){alert(err.message)}finally{e.currentTarget.disabled=false}};window.TDHGlobalNav?.refresh?.()}
async function open(){window.TDHTrackDayMode?.suspend?.();try{current=await call('status');if(nonAttending()){await paintFollower();return}const ready=current.readyAt?Date.parse(current.readyAt):0;if(ready&&Date.now()>=ready){close();await window.TDHTrackDayMode?.open?.();return}paint()}catch(e){console.warn('Pre-event unavailable',e)}}
function close(){document.getElementById('tdhPreEvent')?.remove()}
window.TDHPreEvent={open,close};
})();